### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [Tyjnorris/Capstone#5]
Grade: Meets Expectations

Summary:
Tyler, congrats on finishing your capstone project! Overall you did an excellent job ensuring your page was responsive and incorporating a mobile menu. Apart from this, you did an excellent job integrating all the various tools you encountered thus far. 

I did notice that you did not add any comments in your HTML file and on any future projects I do reccomend that you do as it helps increase the readability of your project. Feel free to take a look at this [HTML](https://gist.github.com/jim-rosales/b47b8a0d64cacf4c0fb4ad91c634eb42) and [CSS](https://gist.github.com/jim-rosales/433c7f33d0345708352940a721c204c2) solution for the project to get an idea of the type of comments you can leave on any future projects.

To expand on your project consider researching the pseudo-classes [hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover), [active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active), and the property [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition). This [codepen](https://codepen.io/JacobStone/pen/GfLEn) might serve as an inspiration to how you can use them all together.   

Apart from these, I'd also highly recommend you read into [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables) and then analyze how you might make use of them on future projects. They are a great tool that allows you to increase the maintainability of your CSS file and it's readability.

**Comment by Tyjnorris** [comment]
Thank you for the review. I've corrected the syntax errors and stylistic errors you pointed out and will look into all of your suggestions as to further my knowledge.
